Expand file tokenisation
nfdi4plants/ARCTokenization pull request #53
Opened 2024-02-24 02:39 UTC by LibraChris

Expand the tokenisation of files and directories as described in #52.

2024-02-26 16:58 UTC, LibraChris commented
@kMutagene

2024-02-27 08:28 UTC, kMutagene requested changes
@LibraChris looks good, but i think we should separate the layers a bit cleaner.

- The API in `FileSystem` should provide a function that simply tokenizes a single URI (e.g. signature `System.Uri -> Cvparam`)
- That weay, the calling function can decide on the type of uris it provides, and we do not need to provide one function for paths and files each here.
- I like the idea of "traversing" ther URI segments, and i think all these match cases could be unified to a single one

2024-02-27 08:28 UTC, kMutagene commented on src/ARCTokenization/Tokenization.fs
> +    module SpecificTokens =
rename SpecificTokens -> ArcFileSystem

2024-02-27 08:28 UTC, kMutagene commented on src/ARCTokenization/Tokenization.fs
> +            let getC (p: string) (segments: string array) =
refactor this to `Uri.toCvParam`

2024-02-27 08:28 UTC, kMutagene commented on src/ARCTokenization/Tokenization.fs
> +            let getC (p: string) =
refactor this to `Uri.toCvParam` (merge with the match cases above)

2024-02-27 08:30 UTC, kMutagene commented on src/ARCTokenization/Tokenization.fs
> +                    if Array.contains "studies" segments then
Also note that ARCtrl provides literal strings for most of these well-defined strings, so we should use those (e.g., reference them in the `Globals` namespace and use those references here)

2024-02-27 14:55 UTC, kMutagene requested changes
after some small naming tweaks and added tests, lgtm

2024-02-27 14:55 UTC, kMutagene commented on src/ARCTokenization/Tokenization.fs
> +    module SpecificTokens =
rename SpecificTokens -> ArcFileSystem

2024-02-27 14:55 UTC, kMutagene commented on src/ARCTokenization/FileSystem.fs
> +    let private normalisePath (path:string) =
use `internal` instead of `private`

2024-02-27 14:55 UTC, kMutagene commented on src/ARCTokenization/Tokenization.fs
> +        let getSpecificTokens (rootPath:string) (pType:PType) (path:string) =
rename `getSpecificTokens` -> getArcFileSystemTokens

2024-02-27 14:55 UTC, kMutagene commented on src/ARCTokenization/Tokenization.fs
> +        let matchFileSystemTokenByRelativePath (pType:PType) (relativePath: string) =
rename `matchFileSystemTokenByRelativePath` -> `convertRelativePath`

2024-02-28 00:35 UTC, LibraChris commented
@kMutagene 
All ISA.tryParseMetadataSheetFromToken functions are based on the absolute path of a token, either this needs to be adjusted or the ARC Tokenisation should be based on absolute paths

2024-02-28 05:55 UTC, kMutagene commented
> this needs to be adjusted
I would suggest by adding the toot path as argument

2024-02-29 07:42 UTC, kMutagene requested changes
Very nice how this comes together now.

I have a few naming nitpicks. Also, you should adapt the xml documentation for the new token-based top level parsers. Most annotations for the token arguments are 

> /// <param name="absFileToken">he path to the xlsx file</param>

Which is not true.

2024-02-29 07:42 UTC, kMutagene commented on src/ARCTokenization/TopLevelParsers.fs
> +    let tryParseMetadataSheetFromToken (rootPath:string) (isaCvTerm: CvTerm) (isaMdsParsingF: string -> IParam list) (absFileToken: IParam) =
nitpick: rename absFileToken -> relFileToken, since we ar enow tokenizing the farc file system as relative paths by convention

2024-02-29 07:42 UTC, kMutagene commented on src/ARCTokenization/TopLevelParsers.fs
> +    let parseMetadataSheetsFromTokens (rootPath:string) (isaCvTerm: CvTerm) (isaMdsParsingF: string -> IParam list) (absFileTokens: #IParam seq) =
absFileToken -> relFileToken

2024-02-29 07:42 UTC, kMutagene commented on src/ARCTokenization/TopLevelParsers.fs
> +    let parseProcessGraphColumnsFromToken (rootPath:string) (absFileToken: IParam) =
absFileToken -> relFileToken

2024-02-29 07:42 UTC, kMutagene commented on src/ARCTokenization/TopLevelParsers.fs
> +    let parseProcessGraphColumnsFromTokens (rootPath:string) (isaCvTerm: CvTerm) (absFileTokens: #IParam seq) =
absFileTokens -> relFileTokens

2024-02-29 07:42 UTC, kMutagene commented on src/ARCTokenization/TopLevelParsers.fs
> +    static member parseProcessGraphColumnsFromToken (rootPath:string) (absFileToken: IParam) =
absFileToken -> relFileToken

2024-02-29 07:42 UTC, kMutagene commented on src/ARCTokenization/TopLevelParsers.fs
> +    static member parseProcessGraphColumnsFromTokens (rootPath:string) (isaCsvTerm) (absFileTokens: #IParam seq) =
absFileTokens -> relFileTokens

2024-02-29 07:42 UTC, kMutagene commented on src/ARCTokenization/TopLevelParsers.fs
> +    static member parseProcessGraphColumnsFromToken (rootPath:string) (absFileToken: IParam) =
absFileToken -> relFileToken

2024-02-29 07:42 UTC, kMutagene commented on src/ARCTokenization/TopLevelParsers.fs
> +    /// <param name="absFileToken">he path to the  xlsx file</param>
absFileTokens -> relFileTokens

2024-03-01 09:23 UTC, kMutagene requested changes

2024-03-01 09:23 UTC, kMutagene commented on src/ARCTokenization/TopLevelParsers.fs
> +    static member parseProcessGraphColumnsFromTokens (rootPath:string) (refFileTokens: #IParam seq) =
The xml comments still do not help that much. 

> IParam seq of the ARC Tokens

says nothing to me. 

Also 

> Returns a seq of annotation tables from an IParam seq if the given tokens contains a filepath with the standard assay file name ("isa.assay.xlsx") 

is only technically true, as we now match the term. So i would suggest something like this:

> Returns a seq of annotation tables from an IParam seq for each contained token that is annotated with the term 'Assay File' (e.g, files in the ARC named `isa.assay.xlsx`).

and for refFileToken**s** (typo there as well)

> a seq of IParams that may contain relevant tokens

2024-03-01 14:56 UTC, kMutagene commented on src/ARCTokenization/TopLevelParsers.fs
> +            | 0 -> Seq.empty
convoluted way of just returning x :D

2024-03-01 14:57 UTC, kMutagene approved these changes

2024-03-02 08:21 UTC, merged