Code generation
nfdi4plants/ARCTokenization pull request #56
Opened 2024-02-27 09:26 UTC by omaus

This PR
- adds functions for code generation (from OBO files to F# source files)
- closes #55 

Left to do:
- unit tests
- (GitHub action for automatized execution)

2024-03-14 08:11 UTC, kMutagene requested changes
Looks good so far, with minor changes.

Also, please incorporate code generation into the build process, so that the `.fs` files for the ontologies get generated the same way we currently generate the `.obo` files from `yml` 
see https://github.com/nfdi4plants/ARCTokenization/blob/e5280af758f71d54c0414f8c2af492d8bc7cedf4/build/BasicTasks.fs#L37

This most likely means that the code generation must move into a separate project, as we must execute it before building the other projects that should contain the generated `.fs` files. ideally, make it a console application so we can just build and run it via a fake process

2024-03-14 08:11 UTC, kMutagene commented on codeGenTestScript.fsx
> +toSourceCode onto
Please stop committing test scripts to repos. Pls refactor anything relevant to actual unit tests or do not commit it at all.

2024-03-14 08:11 UTC, kMutagene commented on playground.fsx
> +        [""; "Maus"; "Keider"; "müller"; "oih"]
you seriously need to fix your encoding problems 😆

2024-04-19 11:47 UTC, kMutagene requested changes
My initial idea for this has been adding a separate runnable project (basically the same type as the build project) and invoking that from within the build project's pipelines.

However, looking at this PR, i think it would be best to set up OBO.NET.CodeGeneration as a completely separate library. This way, we can cleanly add a dependency to that package in the build project, keep the rest as-is, and also make code generation from obo files usable in other projects. Additionally, we do not bloat this repo further with another project.

I think the only thing to adapt code-wise would be parameterizing the namespace of the generated files.

What do you think @omaus?

2024-04-19 11:47 UTC, kMutagene commented on build/BasicTasks.fs
> +open ARCTokenization.StructuralOntology
While it seems to work, i really do not like this circular dependency, where the build project is dependent on one of the projects it is supposed to build.

2024-05-24 13:46 UTC, omaus commented
> My initial idea for this has been adding a separate runnable project (basically the same type as the build project) and invoking that from within the build project's pipelines.
> 
> However, looking at this PR, i think it would be best to set up OBO.NET.CodeGeneration as a completely separate library. This way, we can cleanly add a dependency to that package in the build project, keep the rest as-is, and also make code generation from obo files usable in other projects. Additionally, we do not bloat this repo further with another project.
> 
> I think the only thing to adapt code-wise would be parameterizing the namespace of the generated files.
> 
> What do you think @omaus?

Closed due to this and since the functionality is already realized in [OBO.NET](https://github.com/CSBiology/OBO.NET/pull/32).

2024-05-24 13:46 UTC, closed without merging